server:
  port: 8187
  servlet:
    context-path: /web-market-cart
utils:
  cart:
    prefix: SPRING_WEB_
spring:
  application:
    name: cart-service
integrations:
  core-service:
    url: http://localhost:5555/core/api/v1